# Site settings
title: وبلاگ داریوش عباسی
email: poshtehani+farsiblog@gmail.com
description: > # this means to ignore newlines until "baseurl:"

baseurl: "/farsi/" # the subpath of your site, e.g. /blog/
url: "http://dariubs.github.io" # the base hostname & protocol for your site
twitter_username: dariubs
github_username:  dariubs

# Build settings
markdown: kramdown

timezone: Asia/Tehran
encoding: utf-8

